package me.phie.tawc.install.distro.manjaro

import me.phie.tawc.install.BootstrapFormat
import me.phie.tawc.install.BootstrapVerification
import me.phie.tawc.install.Installation
import me.phie.tawc.install.InstallationMethod
import me.phie.tawc.install.distro.Distro
import me.phie.tawc.install.distro.DistroBootstrap
import me.phie.tawc.install.distro.arch.ArchPacmanCommon

/**
 * Manjaro ARM (aarch64). Bootstrap is the official manjaro-arm/rootfs
 * GitHub release — `Manjaro-ARM-aarch64-latest.tar.gz`, weekly auto-
 * built by Manjaro's CI, ~210 MB compressed. The latest tag's asset
 * URL and SHA-256 are looked up via the GitHub Releases REST API at
 * install time; see [resolveBootstrap].
 *
 * Unlike ALARM, the Manjaro ARM bootstrap is minimal — no kernel
 * package, no firmware, no editors, no openssh — so the per-distro
 * cruft list is empty (the shared list in [ArchPacmanCommon] filters
 * by `pacman -Qq` first, so passing entries that aren't installed is
 * harmless).
 *
 * Three keyrings are populated together (`archlinuxarm manjaro
 * manjaro-arm`), matching what Manjaro's own manjaro-docker image
 * does. All three are shipped in the bootstrap under
 * `/usr/share/pacman/keyrings/`.
 */
internal object ManjaroArm : Distro {
    override val key: String = Installation.DISTRO_MANJARO
    override val displayName: String = "Manjaro ARM"
    override val defaultLabel: String = "Manjaro"
    override val linuxArch: String = "aarch64"
    override val androidAbi: String = "arm64-v8a"

    /**
     * Static placeholder — the real URL and digest are resolved at
     * install time in [resolveBootstrap]. We still need a default
     * here because [Distro.bootstrap] is part of the interface (used
     * by code paths that may want a hint without paying the API
     * round-trip, e.g. a future "show download size" UI).
     */
    override val bootstrap: DistroBootstrap = DistroBootstrap(
        url = "https://github.com/manjaro-arm/rootfs/releases/latest/download/Manjaro-ARM-aarch64-latest.tar.gz",
        format = BootstrapFormat.GZIP,
        stripPrefix = null,
        // Placeholder digest — never used. resolveBootstrap returns a
        // fresh DistroBootstrap with the live SHA-256 from the API.
        verification = BootstrapVerification.None,
    )

    override fun resolveBootstrap(log: (String) -> Unit): DistroBootstrap {
        log("manjaro-arm: resolving latest release via GitHub API")
        val asset = GitHubReleaseResolver.resolveLatest(
            owner = "manjaro-arm",
            repo = "rootfs",
            assetName = "Manjaro-ARM-aarch64-latest.tar.gz",
        )
        log("manjaro-arm: latest=${asset.downloadUrl} sha256=${asset.sha256Hex}")
        return DistroBootstrap(
            url = asset.downloadUrl,
            format = BootstrapFormat.GZIP,
            stripPrefix = null,
            verification = BootstrapVerification.Sha256(asset.sha256Hex),
        )
    }

    override val basePackages: List<String> = ArchPacmanCommon.DEFAULT_BASE_PACKAGES

    /**
     * Manjaro's stock mirrorlist (shipped with the bootstrap) is
     * generated by `pacman-mirrors --fasttrack` and lists ~30 mirrors;
     * our config step rewrites it to a curated short list of HTTPS
     * endpoints with proper TLS certs. Pacman's own SigLevel
     * (Required-DatabaseOptional, kept from upstream pacman.conf) is
     * the integrity barrier on every package fetched here, so the
     * mirrorlist's job is just availability + reasonable freshness,
     * not authentication.
     *
     * **Why `arm-testing` and not `arm-stable`:** Manjaro ARM's stable
     * channel has `glibc-2.35-5.1` (frozen on the mirror since
     * 2022-05-31, ~4 years stale), which is too old to satisfy our
     * libhybris build — `libhybris-common.so.1` references symbols
     * at the GLIBC_2.38 version, so `ldd /usr/local/lib/libEGL.so.1`
     * reports `version 'GLIBC_2.38' not found` and every EGL/GLES
     * client fails to launch. `arm-testing` ships `glibc-2.41+`,
     * which satisfies the version requirement; it's still a vetted
     * channel (between -stable and -unstable) so the update churn is
     * tolerable. The first `pacman -Syyu` after install bumps glibc
     * (and many transitive packages) to current versions.
     */
    private val MIRROR_LIST: String = listOf(
        "Server = https://mirror.alwyzon.net/manjaro/arm-testing/\$repo/\$arch",
        "Server = https://manjaro.repo.cure.edu.uy/arm-testing/\$repo/\$arch",
        "Server = https://mirror.futureweb.be/manjaro/arm-testing/\$repo/\$arch",
        "Server = https://ftp.linux.org.tr/manjaro/arm-testing/\$repo/\$arch",
        "Server = https://mirrors.dotsrc.org/manjaro/arm-testing/\$repo/\$arch",
    ).joinToString("\n")

    /**
     * Defence-in-depth `IgnorePkg` — Manjaro ARM's bootstrap doesn't
     * ship any kernel/firmware packages, but this keeps a future
     * `pacman -Syu` from picking them up if some package marks them
     * as an optional dep (e.g. installing a userland tool that wants
     * a `linux` dep). Globs are honoured by pacman.
     */
    private val IGNORED_PACKAGES = listOf(
        "linux", "linux-aarch64", "linux-rpi*", "linux-firmware", "linux-firmware-*",
    )

    /**
     * Empty: Manjaro ARM's bootstrap is already minimal (93 packages,
     * no kernel/firmware/editors). The shared [ArchPacmanCommon]
     * cruft list is filtered by `pacman -Qq` first, so we don't need
     * to add anything per-arch.
     */
    private val ARCH_SPECIFIC_CRUFT: List<String> = emptyList()

    override fun configure(method: InstallationMethod, rootfs: String, log: (String) -> Unit) =
        ArchPacmanCommon.configure(method, rootfs, MIRROR_LIST, IGNORED_PACKAGES, log)

    override fun initPackageManager(method: InstallationMethod, rootfs: String, log: (String) -> Unit) =
        // Three keyrings: archlinuxarm (upstream sync), manjaro
        // (Manjaro main x86), manjaro-arm (Manjaro ARM-specific).
        // All shipped in the bootstrap under /usr/share/pacman/keyrings/.
        ArchPacmanCommon.initPackageManager(
            method,
            rootfs,
            keyring = "archlinuxarm manjaro manjaro-arm",
            archSpecificCruft = ARCH_SPECIFIC_CRUFT,
            log = log,
        )

    override fun installBasePackages(method: InstallationMethod, rootfs: String, log: (String) -> Unit) =
        ArchPacmanCommon.installBasePackages(method, rootfs, basePackages, log)
}
